### ISSUE TITLE
What should I do if the 3D model is damaged when importing into the project?

### ISSUE THREAD

**Issue by Goshanchick** [PenguinMod/PenguinMod-Packager#11]
I made a Luntik model in AutoDesk for the game, and then decided to download it. Converted to a uri and got black snot! Everything is stable at AutoDesk. (I'm using .fbx, if it helps)

**Comment by rttyg46305Unj** [comment]
just use obj

**Comment by SharkPool-SP** [comment]
closing for now as its an older issue. Also, the 3d extension is not finished. You should not be surprised if things don't work
