### ISSUE TITLE
The camera never works on my packaged game.

### ISSUE THREAD

**Issue by MunaAlaneme** [PenguinMod/PenguinMod-Packager#12]
Every time I package my game, the camera never works because it was never open-sourced and I couldn't find it. Please, can you locate the camera.js file?

**Comment by MunaAlaneme** [comment]
Nvm, I fixed it, except for that wierd size glitch.

**Comment by RedMan13** [comment]
> Every time I package my game, the camera never works because it was never open-sourced and I couldn't find it. Please, can you locate the camera.js file?

i would like to know what camera extension you are referring to as all of penguinmod and turbowarps extensions are opensource

**Comment by MunaAlaneme** [comment]
I was using PM Camera, now TW Camera fixed it.
